package com.cinema.model.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_PROCESSING,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    SHOWTIME_UPDATED,
    MOVIE_ADDED,
    MOVIE_UPDATED,
    MOVIE_DELETED,
    SYSTEM_NOTIFICATION
} 